function! ToggleColors()
  if &background == 'dark'
    colorscheme bclear
  else
    colorscheme jellybeans
  end
endfunction

IndentGuidesEnable
colorscheme jellybeans

map <Leader>C :call ToggleColors()<CR>

set guioptions-=T " Hide the tool bar

" MacVim
if has("gui_macvim")
  set guifont=Monaco:h16

  " Disable scrollbars
  set guioptions-=rL
endif

" Cursor
set guicursor=a:blinkon0 " turn off cursor blink
set guicursor+=i:ver25-iCursor " colour cursor in insert mode
set guicursor+=c:block-cCursor " colour cursor in command mode
