function! ToggleColors()
  if &background == 'dark'
    colorscheme bclear
  else
    colorscheme paradox
  end
endfunction

IndentGuidesEnable
colorscheme paradox
let g:mimic_paradox_alt=1
color paradox

map <Leader>C :call ToggleColors()<CR>

set guioptions-=T " Hide the tool bar

" MacVim
if has("gui_macvim")
  set guifont=Monaco:h11

  " Disable scrollbars
  set guioptions-=rL
endif

" Cursor
set guicursor=a:blinkon0 " turn off cursor blink
set guicursor+=i:ver25-iCursor " colour cursor in insert mode
set guicursor+=c:block-cCursor " colour cursor in command mode

" JSX highlighting in JS files
let g:jsx_ext_required = 0
let g:airline#extensions#tabline#enabled = 1
