set guioptions-=T " Hide the tool bar

"set macligatures

" MacVim
if has("gui_macvim")
  set guifont=Monaco:h11
  set guifont=Monaco\ Nerd\ Font\ Mono:h11 " for ryanoasis/vim-devicons
  " Disable scrollbars
  set guioptions-=rL
endif

" Cursor
set guicursor=a:blinkon0 " turn off cursor blink
set guicursor+=i:ver25-iCursor " colour cursor in insert mode
set guicursor+=c:block-cCursor " colour cursor in command mode

let g:NERDTreeHijackNetrw=1
let NERDTreeHijackNetrw=1

let g:gitgutter_override_sign_column_highlight = 0
